[package]
name = "dylan/orthogonalframeworkv2"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ProfileService = "surnautica/profileservice@1.0.0"
Signal = "sleitnick/signal@2.0.1"
Promise = "evaera/promise@4.0.0"
Net = "sleitnick/net@0.2.0"
Janitor = "howmanysmall/janitor@1.15.7"
Sift = "csqrl/sift@0.0.9"

Stew = "data-oriented-house/stew@5.6.0"
Sandwich = "data-oriented-house/sandwich@2.2.1"
Squash = "data-oriented-house/squash@1.1.6"
TableValue = "data-oriented-house/tablevalue@3.0.0"
Cmdr = "evaera/cmdr@1.12.0"

Fusion = "elttob/fusion@0.3.0"
